// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Dynamic = {};

var $$Error = {};

var Head = {};

var $$Image = {};

var Link = {};

var Router = {};

var Res = {};

var GetServerSideProps = {
  Res: Res
};

var GetStaticPaths = {};

var GetStaticProps = {};

var Page = {
  GetServerSideProps: GetServerSideProps,
  GetStaticPaths: GetStaticPaths,
  GetStaticProps: GetStaticProps
};

var Script = {};

exports.Dynamic = Dynamic;
exports.$$Error = $$Error;
exports.Head = Head;
exports.$$Image = $$Image;
exports.Link = Link;
exports.Router = Router;
exports.Page = Page;
exports.Script = Script;
/* No side effect */
