// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function $$default(props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "getServerSideProps & data-driven-dependencies"), React.createElement("h2", undefined, props.data));
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: {
                data: "WIP"
              }
            });
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.getServerSideProps = getServerSideProps;
/* react Not a pure module */
